### PR TITLE
Allow *nix developers to build KoGrid.

### PR DESCRIPTION
**Pull request by lhope**
build.sh bash script for *nix and modified build-order.txt to use the correct case. This allows *nix developers to test modifications much more easily.

build-order.txt contained a few lines with incorrect case. Just fine for Windows, but no good for linux. Please test the modified build-order.txt on windows before accepting.

The output KoGrid-debug.js is equivalent, except for some altered comments and whitespace added in. I used a visual diff program to verify.

### CODE REVIEW

**Comment by orneryd** [comment]
Thanks! this is a great addition.

**Comment by zbrong** [comment]
the pagerLastButton dont display in firefox.

**Comment by zbrong** [comment]
the pagerLastButton dont display in firefox.

**Comment by lhope** [comment]
Is that actually anything to do with this issue (build on linux)?

**Pull request merged**
