### PR TITLE
Use a timeout for smoother scrolling

### PR DESCRIPTION
**Pull request by etishor**
Hi Eric,

I've added a timeout to the scroll event to avoid updating the grid while the user scrolls. Let me know what you think.

Thanks,
Iulian

### CODE REVIEW

**Comment by ericmbarnard** [comment]
@etishor 

I had this type of logic in a previous build of KoGrid (I agree the logic behind doing this makes sense), however when i would grab the scroll bar and drag down on a long list of items, it would blank out the grid.

I'll take a look at these changes and see how the user experience looks now - thanks for this.

-Eric

**Comment by etishor** [comment]
It could also be a setting that the user can change, since for grids with small number of records it's better to scroll right away, but if you need to display 10k+ rows in IE then i think delaying the scroll and showing and empty grid is better than lagging behing user's the scroll movement.

**Comment by ericmbarnard** [comment]
@etishor 

Thats a fair assessment. I primarily use Chrome and IE to develop in. What browser do you use?... as I've obviously noticed differences in the feel of scrolling between those 2 browsers. IE could probably be better w/ the timeout ... however Chrome is so fast its still not that noticeable (but that could be my machine as well)

**Comment by etishor** [comment]
I use Chrome for development, but for the current application i target IE9 primary and IE8 secondary and the grids need to support ~10K rows. I've been using the timeout for the last days and i got used to it. I also have the rows colored and once i've set the bg color of the grid the the same color as the rows the "effect" is not bad. On IE i think is definitely providing a much better experience, as the scroll handle is never stuck.

**Comment by orneryd** [comment]
This is implemented in the skogrid-merge branch

**Pull request closed without merging**
