### PR TITLE
Skogrid merge

### PR DESCRIPTION
**Pull request by orneryd**
Opening the pull request for skogrid merge into master. We can discuss the changes and potential impact and results of unit/functionality tests here before the actual merge.

### CODE REVIEW

**Comment by orneryd** [comment]
the unit tests all pass except for when the no globals flag was popped. one test failed then

Grid Tests: Basic Grid Test (1, 2, 3)Rerun
Introduced global variable(s): newDim

**Comment by orneryd** [comment]
all unit tests pass now.

**Comment by ericmbarnard** [comment]
@Crash8308 

I just pushed some changes for the arrow key navigation logic. We now no longer use the `myRowEntity` pointer, and we can pull out the `getElementsByAttribute` function as I now have the arrow-key events being subscribed in the `GridManager` (where all the other grid-level events are subscribed)

**Comment by orneryd** [comment]
unit test 51 for selection "De-select some items, then select-all should re-select all" fails because the test logic doesn't apply anymore to the new selection logic. I updated the other tests but this one will require some thought. However, It works testing it manually.

**Comment by orneryd** [comment]
what about versioning the file name? as of right now it is just kogrid.debug. I propose we rename it similar to knockout conventions:

koGrid-1.2.0.debug.js 

I created a new branch off main, "1.1.0",  to preserve the existing version

**Pull request merged**
