### PR TITLE
Fix for issue #109

### PR DESCRIPTION
**Pull request by lhope**
The code to add a column's headerTemplate to the kg.templateManager was missing. I copied the code from cellTemplate and my test code started working.

### CODE REVIEW

**Comment by EntitySpaces** [comment]
Awesome, I was trying everything I could to get a headerTemplate to work the other day and gave up, I'm hoping this gets merged and new build cut so I can give it a try.

**Comment by lhope** [comment]
Thanks for the feedback. :)

It is easy enough to give it a try. Just look at the change I made under "Files Changed" and copy it into your local KoGrid-debug.js file. It was a simple enough fix.

**Comment by EntitySpaces** [comment]
Do you have an example of a headerTemplate, there are samples for cell templates but none for headerTempates. For instance, a cellTemplate looks like this:

<script type="text/html" id="editTemplate">
    <div data-bind="kgCell: $cell">
        <input type="text" data-bind="value: $cellValue" style="width: 120px;"/>
    </div>
</script>

I'm sure a header template doesn't use kgCell: $cell  ??

**Comment by lhope** [comment]
I derived my header cell template from the default one here:

https://github.com/ericmbarnard/KoGrid/blob/master/src/Templates/HeaderCellTemplate.js

**Comment by ericmbarnard** [comment]
@EntitySpaces Mike- 

I copied the template below from the Examples page. One thing that we don't have documented yet, is that the HeaderCellTemplates are different from the regular cell templates. CellTemplates are optimized for perf, but HeaderCellTemplates are not, and are much closer to regular KO Templates.

The `$data` that is passed to a HeaderCellTemplate is the instance of a HeaderCell class (and `$parent` is the row). See: https://github.com/ericmbarnard/KoGrid/blob/master/src/GridClasses/HeaderCell.js

``` html
<div id="customHdrTmpl">
     <div data-bind="click: $data.sort, 
          css: { kgSorted: !$data.noSortVisible() }">
          <span data-bind="text: $data.displayName"></span>  
          <img class="kgSortImg" data-bind="visible: $data.noSortVisible" src="data:image/png;base64,iVBOR..."/>
          <img class="kgSortImg" data-bind="visible: $data.sortAscVisible" src="data:image/png;base64,iVBOR..."/>
          <img class="kgSortImg" data-bind="visible: $data.sortDescVisible" src="data:image/png;base64,iVBOR..."/>
     </div>
     <div data-bind="visible: $parent.filterVisible">
          <input type="text" data-bind="value: $data.column.filter, 
               valueUpdate: 'afterkeydown'" 
               style="width: 80%" tabindex="1" />
     </div>
</div>
```

**Comment by orneryd** [comment]
Templates are completely different in version 2.0

**Pull request closed without merging**
