### PR TITLE
Merging changes and new features

### PR DESCRIPTION
**Pull request by orneryd**
Added arrow key up/down selection
Revamped selection logic to enable ctrl/shift selections (no more scalar "selectedItem" observable, only the array version is returned. use index 0 when using single select mode. )
ColumnDefs are now observable and the grid re-initializes if the observable changes
code cleanup and minor bug fixes
added "filterable" option to the column definitions, if false the filter will not appear over the column.
when paging and filtering the page will flip back to page 1 as filters are applied.

### CODE REVIEW

**Comment by thelinuxlich** [comment]
+1

**Comment by ericmbarnard** [comment]
Ok - so I'm thinking in order to get this to merge ... I need to change the master branch to LF line-endings so that the diff is understandable.

From there, I'll review and we can edit this fork until we're ready to merge w/ master.

**Comment by orneryd** [comment]
should be fine. I just had a breakthrough in column width resizing, see my
latest commit for details.

On Mon, Aug 27, 2012 at 7:12 PM, Eric Barnard notifications@github.comwrote:

> Ok - so I'm thinking in order to get this to merge ... I need to change
> the master branch to LF line-endings so that the diff is understandable.
> 
> From there, I'll review and we can edit this fork until we're ready to
> merge w/ master.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericmbarnard/KoGrid/pull/65#issuecomment-8077366.

## 

-Tim Sweet

**Comment by ericmbarnard** [comment]
@Crash8308 

Ok - so I've gone through the code and we definitely have some work to do.
1. I need the Unit Tests to pass before we can merge this in. It's my only guarantee to current users that they we aren't breaking current functionality in production. It currently appears that the `FilterManager_Tests` have the most
2. I think I understand why you initially pulled out the `selectedItem` logic, however that is actually needed by several folks I've worked with. I'm fine with possibly working in some kind of `writeable ko.computed` that is just a wrapper around the selectedItems array
3. We'll need to do some work to refactor things so they are test-able, but I'm fine with doing that after we get these things merged.

This Pull Request helped see what items diff between your repo fork and the current master branch, however going forward we might want to setup many small branches off of the master branch and work these bits in piece by piece. If we do that, I can help massage the code, but right now I can't actually edit your fork before the merge.

**Comment by orneryd** [comment]
I can add you to my repo if you want

**Comment by orneryd** [comment]
I added you to my repo and I branched it (which i should have done earlier) so if you make any changes make it to the dev branch. the current version on main is what we are using at work and it is stable for us.

**Comment by ericmbarnard** [comment]
Closing in favor of PR #66 (we don't want to merge straight into 'master' just yet... )

**Pull request closed without merging**
